### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by svanzoest** [svanzoest-cookbooks/accounts#3]
Hi @bitfag,

I added you as a collaborator for starters. Do you have a supermarket.chef.io account that I could add to https://supermarket.chef.io/cookbooks/accounts ?

**Comment by bitphage** [comment]
18.02.2017, 07:03, "Sander van Zoest" <notifications@github.com>:Hi @bitfag,I added you as a collaborator for starters. Do you have a supermarket.chef.io account that I could add to https://supermarket.chef.io/cookbooks/accounts ?  OK, my supermarket account is "vvk".

**Comment by svanzoest** [comment]
Hi Vladimir,

I transferred the cookbook to you. Can you rename/delete your local branch on github, so I can also transfer you the cookbook on github?

**Comment by bitphage** [comment]
19.02.2017, 01:41, "Sander van Zoest" <notifications@github.com>:
> Hi Vladimir,
>
> I transferred the cookbook to you. Can you rename/delete your local branch on github, so I can also transfer you the cookbook on github?

Done.

**Comment by svanzoest** [comment]
Transfer initiated.

**Comment by bitphage** [comment]
19.02.2017, 15:33, "Sander van Zoest" <notifications@github.com>:
> Transfer initiated.

Github had some issues with repository transfer, could you please repeat the transfer? Previous one had expired.

**Comment by svanzoest** [comment]
I have initiated a new transfer. Hopefully this one will succeed.

**Comment by svanzoest** [comment]
Let me know if there is anything I can do to help, of course.
